version: '3'
services:
  wms:
    container_name: wms
    build: .
    image: wms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: wmsDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    # depends_on:
    #   - wmsDB

  # wmsDB:
  #   container_name: wmsDB
  #   platform: linux/amd64 #for platform error on Apple M1 chips
  #   restart: unless-stopped
  #   env_file: .env
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_USER: ${DATABASE_USERNAME}
  #     MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #     MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  #     MYSQL_DATABASE: ${DATABASE_NAME}
  #     MYSQL_ROOT_HOST: '%'
  #   volumes:
  #     - "./data:/var/lib/postgresql/data/" # if you want to use a bind folder
  #   ports:
  #     - '3306:3306'

