
name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute remote script
      uses: appleboy/ssh-action@master
      env:
        HOME: /home/ubuntu
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ubuntu
        envs: HOME
        key: ${{ secrets.REMOTE_KEY }}
        script: "cd $HOME/erp && bash deploy.sh"
